##
# ci-renovate.yaml
# Automates dependency updates using Renovate.
##
---
name: Call renovate bot
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Override default log level'
        required: false
        default: 'info'
        type: string
      overrideSchedule:
        description: 'Override all schedules'
        required: false
        default: 'false'
        type: string

  # Runs at least 30 mins at 4am every day
  schedule:
    - cron: '30 4 * * *'

jobs:
  call-ci-renovate:
    name: Renovate
    uses: sosadtsia/workflow-templates/.github/workflows/ci-renovate.yaml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets:
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
    with:
      logLevel: ${{ inputs.logLevel || 'info' }}
      overrideSchedule: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
